#### GET request to example server
#
POST http://localhost:4000/api/patients/create
Content-Type: application/json

{
  "name": "Faisal",
  "email":"faisal@universe.com",
  "address": "Canada",
  "dateOfBirth": "2009-09-25",
  "registeredDate": "2026-07-13"
}